First we initialize a set of N numbers and a random target.

In [18]:
import random

N = 10

k = 5 # number of digits in target in base N representation

target = random.randint(N**(k-1),N**k -1)

list_Num = [] 

for i in range(N) :
    list_Num.append(random.randint(0,target-1))
    
print(target)
print(list_Num)

69665
[62229, 39616, 61332, 3011, 46137, 37957, 36785, 42763, 47276, 36398]


Now let's initialize k number of tables with N^2 rows and N columns to solve the problem 1 digit at a time with DP setup. First let's try with N rows and columns for the unit digits only.

In [19]:
import numpy as np

Data_Table = np.zeros((N,N))

print(Data_Table)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Initialize 0 column to be 1. 

In [23]:
Data_Table[:,0] = 1

print(Data_Table)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Now initialize through table and fill out Data Table

In [30]:
mod = list_Num[0] - 10*int(list_Num[0]/10)

Data_Table[0,mod] = 1

for i in range(1,N) :
    mod = list_Num[i] - 10*int(list_Num[i]/10)
    Data_Table[i,mod] = 1
    for j in range(1,N) :
        if (Data_Table[i-1,j] == 1) :
            Data_Table[i,j] = 1
            mod2 = j + mod
            mod2 = mod2 - 10*int(mod2/10)
            Data_Table[i,mod2] = 1

print(Data_Table)

9
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Okay so seems to be working as expected. Now we need to expand this to include N^2 rows so we can partition the entire set into k-1 such tables. The first and last table are special. The first table will have single entry at end while the last table will have different operations and be able to remove sums.

In [35]:
Data_Table_K = np.zeros((N,N**2,k-1))

Data_Table_K[:,0,:] = 1

for ki in range(k-2) :
    
    mod = int(list_Num[0]/10**ki) - 100*int(int(list_Num[0]/10**ki)/100)
    
    Data_Table_K[0,mod,ki] = 1
    
    for i in range(1,N) :
        
        mod = int(list_Num[i]/10**ki) - 100*int(int(list_Num[i]/10**ki)/100)
    
        Data_Table_K[i,mod,ki] = 1
    
        for j in range(1,N**2) :
            
            if (Data_Table_K[i-1,j,ki] == 1) :
                Data_Table_K[i,j,ki] = 1
                mod2 = j + mod
                mod2 = mod2 - 100*int(mod2/100)
                Data_Table_K[i,mod2,ki] = 1
    
print(Data_Table_K[:,:,0])


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.

In [ ]:
Data_Table_K = np.zeros((N,N**2,k-1))

Data_Table_K[:,0,:] = 1

for ki in range(k-1) :
    
    mod = int(list_Num[0]/10**ki) - 100*int(int(list_Num[0]/10**ki)/100)
    
    Data_Table_K[0,mod,ki] = 1
    
    
for i in range(1,N) :
     
    mod = int(list_Num[i]/10**(k-1)) - 100*int(int(list_Num[i]/10**(k-1))/100)
    
    Data_Table_K[i,mod,(k-1)] = 1
        
    for ki in range(k-2):
        
        mod = int(list_Num[i]/10**ki) - 100*int(int(list_Num[i]/10**ki)/100)
    
        Data_Table_K[i,mod,ki] = 1
    
        for j in range(1,N**2) :
            
            if (Data_Table_K[i-1,j,ki] == 1) :
                Data_Table_K[i,j,ki] = 1
                mod2 = j + mod
                mod2 = mod2 - 100*int(mod2/100)
                Data_Table_K[i,mod2,ki] = 1
    
print(Data_Table_K[:,:,0])
